# https://github.com/HIT-K1928-LAB/Fast-Drone-XI35.git Docker/Dockerfile/Dockerfile.pc
FROM fastdronexi35:pc

LABEL org.opencontainers.image.authors="zhangrun <1139135655@qq.com>"
LABEL org.opencontainers.image.description="ROS Noetic + CUDA + CUDNN + TensorRT environment + miniconda"

# Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh && \
    bash /tmp/miniconda.sh -b -p /opt/conda && \
    rm /tmp/miniconda.sh

RUN /opt/conda/bin/conda init bash
RUN /opt/conda/bin/conda config --set auto_activate_base false && \
    /opt/conda/bin/conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main && \
    /opt/conda/bin/conda config --set show_channel_urls yes
RUN /opt/conda/bin/conda clean -afy

# 默认 shell 使用 bash
SHELL ["/bin/bash", "-c"]